apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "starter-kit.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "starter-kit.name" . }}
    helm.sh/chart: {{ include "starter-kit.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "starter-kit.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "starter-kit.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        prometheus.io/path: {{.Values.route.path}}/metrics
        prometheus.io/port: "{{ .Values.image.port }}"
        prometheus.io/scrape: 'true'
    spec:
      {{- if .Values.image.secretName }}
      imagePullSecrets:
        - name: {{ .Values.image.secretName }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.image.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{.Values.route.path}}/health
              port: http
          readinessProbe:
            httpGet:
              path: {{.Values.route.path}}/health
              port: http
          env:
            - name: INGRESS_HOST
              value: ""
            - name: PROTOCOLS
              value: ""
            - name: APP_LOG_LEVEL
              valueFrom: 
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: APP_LOG_LEVEL
            - name: EXPRESS_LOG_LEVEL
              valueFrom: 
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: EXPRESS_LOG_LEVEL
            - name: CLOUDANT_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: binding-{{ .Values.resourceGroupName }}-{{ .Release.Namespace }}-cloudant
                  key: binding
            - name: APPID_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: binding-{{ .Values.resourceGroupName }}-{{ .Release.Namespace }}-appid
                  key: binding
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
